### ISSUE TITLE
[meta-issue] Optimizations

### ISSUE THREAD

**Issue by MerryMage** [MerryMage/dynarmic#22]
List of things to do in order of priority.
### High
- [x] Return Stack Buffer
### Medium
- [ ] Local `pc` cache for instructions currently requiring `ReturnToDispatch`
- [ ] Use host flags
- [x] Get/Set-elimination for Extended Registers (requires special handling)
- [x] Access page-table directly for memory access.
### Low
- [ ] Constant folding
- [x] Replace memory reads to read-only locations with immediates
- [ ] Keep track of sexting, zexting and FTZing
### Ideas
- [ ] IR instruction merging
- [ ] Basicblocks having multipile exits

**Comment by MerryMage** [comment]
Meta-issue has been split into issues #86, #87, #88, #90.
